apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
  namespace: site
  labels:
    app: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: "harbor.getapp.sh/getapp-dev/site:{{ .Values.imageTag }}"
        ports:
        - containerPort: 8000
